"""empty message

Revision ID: 096c51ddc9de
Revises: 01042e4cf64f
Create Date: 2023-02-26 15:22:58.965142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096c51ddc9de'
down_revision = '01042e4cf64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_detection',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('age', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('identification', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_detection')
    # ### end Alembic commands ###
