"""empty message

Revision ID: 44c8c6cd5d81
Revises: 096c51ddc9de
Create Date: 2023-02-26 15:27:58.938378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c8c6cd5d81'
down_revision = '096c51ddc9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_detection', schema=None) as batch_op:
        batch_op.alter_column('identification',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_detection', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.alter_column('identification',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
